config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"

  get 'go' => 'home#go'

  resources :attempts

end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  belongs_to :user
  belongs_to :phrase

  before_save do
    self.score = self.get_score
  end

  def get_diff
    Differ.diff_by_word(self.translated, self.phrase.translated)
  end

  def html_diff
    unless self.translated.nil?
      self.get_diff.format_as :html
    end
  end

  def get_score
    score = 0.0
    unless self.translated.nil?
      # compare with source and set score
      h = JSON.parse(self.get_diff.to_json)
      score = 1.0 / (h['raw'].count) if h['raw'].count > 0
    end
    score
  end

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :phrases
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  belongs_to :feed
  has_many   :attempts

  scope :untranslated, -> { where(:translated => nil) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many   :attempts

  def next_attempt

    next_attempt = nil
    last_attempt = self.attempts.last

    # если попытка уже была, но не завершена
    if !last_attempt.nil? && last_attempt.translated.to_s == ''

      # отдаём эту же попытку снова
      next_attempt = last_attempt

    else

      if last_attempt.nil?
        # create first attempt
        last_phrase_id = 0
      else
        # фраза последней попытки
        last_phrase_id = last_attempt.phrase.id
      end

      # получаем следующую по порядку фразу
      phrase = Phrase.where('id > ?', last_phrase_id).first

      # если фраза нашлась
      unless phrase.nil?
        next_attempt = Attempt.create(
          :user   => self,
          :phrase => phrase
        )
      end

    end

    next_attempt

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController

  def update

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def go

    @user = User.first # @TODO current_user
    @attempt = @user.next_attempt

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/go.html.erb
<p>
    <%=h @attempt.phrase.source %>
</p>

<p>
  <textarea id="translated"></textarea>
</p>

<p>
  <input type="button" class="btn btn-default" value=" Done! " id="done-button">
</p>

<p id="phrase_translated">

</p>

<script type="text/javascript">

    $('#done-button').click(function () {

        var translated = $('#translated').val();

        var data = {
            attempt: {
                translated: translated
            }
        };

        $.ajax({
            url: '<%=h attempt_path(@attempt, :format => :json) %>',
            type: 'PATCH',
            data: data,
            success: function (result) {
                console.log(result);
            }
        });

    });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enru</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>